#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistema.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_sistema")]
	public partial class sistemaDataContext : System.Data.Linq.DataContext
	{
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertcategoria(categoria instance);
    partial void Updatecategoria(categoria instance);
    partial void Deletecategoria(categoria instance);
    partial void Inserttb_cliente(tb_cliente instance);
    partial void Updatetb_cliente(tb_cliente instance);
    partial void Deletetb_cliente(tb_cliente instance);
    partial void Inserttb_ordem_compra(tb_ordem_compra instance);
    partial void Updatetb_ordem_compra(tb_ordem_compra instance);
    partial void Deletetb_ordem_compra(tb_ordem_compra instance);
    partial void Inserttb_produto(tb_produto instance);
    partial void Updatetb_produto(tb_produto instance);
    partial void Deletetb_produto(tb_produto instance);
    #endregion
		
		public sistemaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public sistemaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public sistemaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public sistemaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<categoria> categoria
		{
			get
			{
				return this.GetTable<categoria>();
			}
		}
		
		public System.Data.Linq.Table<tb_cliente> tb_cliente
		{
			get
			{
				return this.GetTable<tb_cliente>();
			}
		}
		
		public System.Data.Linq.Table<tb_ordem_compra> tb_ordem_compra
		{
			get
			{
				return this.GetTable<tb_ordem_compra>();
			}
		}
		
		public System.Data.Linq.Table<tb_produto> tb_produto
		{
			get
			{
				return this.GetTable<tb_produto>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.categoria")]
	public partial class categoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_categoria;
		
		private string _cat_descircao;
		
		private EntitySet<tb_produto> _tb_produto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_categoriaChanging(int value);
    partial void Onid_categoriaChanged();
    partial void Oncat_descircaoChanging(string value);
    partial void Oncat_descircaoChanged();
    #endregion
		
		public categoria()
		{
			this._tb_produto = new EntitySet<tb_produto>(new Action<tb_produto>(this.attach_tb_produto), new Action<tb_produto>(this.detach_tb_produto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_categoria", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_categoria
		{
			get
			{
				return this._id_categoria;
			}
			set
			{
				if ((this._id_categoria != value))
				{
					this.Onid_categoriaChanging(value);
					this.SendPropertyChanging();
					this._id_categoria = value;
					this.SendPropertyChanged("id_categoria");
					this.Onid_categoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat_descircao", DbType="NVarChar(50)")]
		public string cat_descircao
		{
			get
			{
				return this._cat_descircao;
			}
			set
			{
				if ((this._cat_descircao != value))
				{
					this.Oncat_descircaoChanging(value);
					this.SendPropertyChanging();
					this._cat_descircao = value;
					this.SendPropertyChanged("cat_descircao");
					this.Oncat_descircaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="categoria_tb_produto", Storage="_tb_produto", ThisKey="id_categoria", OtherKey="id_categoria")]
		public EntitySet<tb_produto> tb_produto
		{
			get
			{
				return this._tb_produto;
			}
			set
			{
				this._tb_produto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_produto(tb_produto entity)
		{
			this.SendPropertyChanging();
			entity.categoria = this;
		}
		
		private void detach_tb_produto(tb_produto entity)
		{
			this.SendPropertyChanging();
			entity.categoria = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_cliente")]
	public partial class tb_cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_cliente;
		
		private string _cli_nome;
		
		private string _cli_apelido;
		
		private System.Nullable<int> _cli_endereco;
		
		private string _cli_cep;
		
		private string _cli_cidade;
		
		private EntitySet<tb_ordem_compra> _tb_ordem_compra;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_clienteChanging(int value);
    partial void Onid_clienteChanged();
    partial void Oncli_nomeChanging(string value);
    partial void Oncli_nomeChanged();
    partial void Oncli_apelidoChanging(string value);
    partial void Oncli_apelidoChanged();
    partial void Oncli_enderecoChanging(System.Nullable<int> value);
    partial void Oncli_enderecoChanged();
    partial void Oncli_cepChanging(string value);
    partial void Oncli_cepChanged();
    partial void Oncli_cidadeChanging(string value);
    partial void Oncli_cidadeChanged();
    #endregion
		
		public tb_cliente()
		{
			this._tb_ordem_compra = new EntitySet<tb_ordem_compra>(new Action<tb_ordem_compra>(this.attach_tb_ordem_compra), new Action<tb_ordem_compra>(this.detach_tb_ordem_compra));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cliente", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_cliente
		{
			get
			{
				return this._id_cliente;
			}
			set
			{
				if ((this._id_cliente != value))
				{
					this.Onid_clienteChanging(value);
					this.SendPropertyChanging();
					this._id_cliente = value;
					this.SendPropertyChanged("id_cliente");
					this.Onid_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cli_nome", DbType="NVarChar(50)")]
		public string cli_nome
		{
			get
			{
				return this._cli_nome;
			}
			set
			{
				if ((this._cli_nome != value))
				{
					this.Oncli_nomeChanging(value);
					this.SendPropertyChanging();
					this._cli_nome = value;
					this.SendPropertyChanged("cli_nome");
					this.Oncli_nomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cli_apelido", DbType="NVarChar(50)")]
		public string cli_apelido
		{
			get
			{
				return this._cli_apelido;
			}
			set
			{
				if ((this._cli_apelido != value))
				{
					this.Oncli_apelidoChanging(value);
					this.SendPropertyChanging();
					this._cli_apelido = value;
					this.SendPropertyChanged("cli_apelido");
					this.Oncli_apelidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cli_endereco", DbType="Int")]
		public System.Nullable<int> cli_endereco
		{
			get
			{
				return this._cli_endereco;
			}
			set
			{
				if ((this._cli_endereco != value))
				{
					this.Oncli_enderecoChanging(value);
					this.SendPropertyChanging();
					this._cli_endereco = value;
					this.SendPropertyChanged("cli_endereco");
					this.Oncli_enderecoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cli_cep", DbType="NVarChar(50)")]
		public string cli_cep
		{
			get
			{
				return this._cli_cep;
			}
			set
			{
				if ((this._cli_cep != value))
				{
					this.Oncli_cepChanging(value);
					this.SendPropertyChanging();
					this._cli_cep = value;
					this.SendPropertyChanged("cli_cep");
					this.Oncli_cepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cli_cidade", DbType="NVarChar(50)")]
		public string cli_cidade
		{
			get
			{
				return this._cli_cidade;
			}
			set
			{
				if ((this._cli_cidade != value))
				{
					this.Oncli_cidadeChanging(value);
					this.SendPropertyChanging();
					this._cli_cidade = value;
					this.SendPropertyChanged("cli_cidade");
					this.Oncli_cidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_cliente_tb_ordem_compra", Storage="_tb_ordem_compra", ThisKey="id_cliente", OtherKey="id_cliente")]
		public EntitySet<tb_ordem_compra> tb_ordem_compra
		{
			get
			{
				return this._tb_ordem_compra;
			}
			set
			{
				this._tb_ordem_compra.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_ordem_compra(tb_ordem_compra entity)
		{
			this.SendPropertyChanging();
			entity.tb_cliente = this;
		}
		
		private void detach_tb_ordem_compra(tb_ordem_compra entity)
		{
			this.SendPropertyChanging();
			entity.tb_cliente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_ordem_compra")]
	public partial class tb_ordem_compra : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_ordem;
		
		private System.Nullable<int> _id_cliente;
		
		private System.Nullable<int> _id_produto;
		
		private EntityRef<tb_cliente> _tb_cliente;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_ordemChanging(int value);
    partial void Onid_ordemChanged();
    partial void Onid_clienteChanging(System.Nullable<int> value);
    partial void Onid_clienteChanged();
    partial void Onid_produtoChanging(System.Nullable<int> value);
    partial void Onid_produtoChanged();
    #endregion
		
		public tb_ordem_compra()
		{
			this._tb_cliente = default(EntityRef<tb_cliente>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_ordem", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_ordem
		{
			get
			{
				return this._id_ordem;
			}
			set
			{
				if ((this._id_ordem != value))
				{
					this.Onid_ordemChanging(value);
					this.SendPropertyChanging();
					this._id_ordem = value;
					this.SendPropertyChanged("id_ordem");
					this.Onid_ordemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cliente", DbType="Int")]
		public System.Nullable<int> id_cliente
		{
			get
			{
				return this._id_cliente;
			}
			set
			{
				if ((this._id_cliente != value))
				{
					if (this._tb_cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_clienteChanging(value);
					this.SendPropertyChanging();
					this._id_cliente = value;
					this.SendPropertyChanged("id_cliente");
					this.Onid_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_produto", DbType="Int")]
		public System.Nullable<int> id_produto
		{
			get
			{
				return this._id_produto;
			}
			set
			{
				if ((this._id_produto != value))
				{
					this.Onid_produtoChanging(value);
					this.SendPropertyChanging();
					this._id_produto = value;
					this.SendPropertyChanged("id_produto");
					this.Onid_produtoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_cliente_tb_ordem_compra", Storage="_tb_cliente", ThisKey="id_cliente", OtherKey="id_cliente", IsForeignKey=true)]
		public tb_cliente tb_cliente
		{
			get
			{
				return this._tb_cliente.Entity;
			}
			set
			{
				tb_cliente previousValue = this._tb_cliente.Entity;
				if (((previousValue != value) 
							|| (this._tb_cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_cliente.Entity = null;
						previousValue.tb_ordem_compra.Remove(this);
					}
					this._tb_cliente.Entity = value;
					if ((value != null))
					{
						value.tb_ordem_compra.Add(this);
						this._id_cliente = value.id_cliente;
					}
					else
					{
						this._id_cliente = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_cliente");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_produto")]
	public partial class tb_produto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_produto;
		
		private string _pro_nome;
		
		private System.Nullable<double> _pro_preco;
		
		private string _pro_marca;
		
		private System.Nullable<int> _id_categoria;
		
		private EntityRef<categoria> _categoria;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_produtoChanging(int value);
    partial void Onid_produtoChanged();
    partial void Onpro_nomeChanging(string value);
    partial void Onpro_nomeChanged();
    partial void Onpro_precoChanging(System.Nullable<double> value);
    partial void Onpro_precoChanged();
    partial void Onpro_marcaChanging(string value);
    partial void Onpro_marcaChanged();
    partial void Onid_categoriaChanging(System.Nullable<int> value);
    partial void Onid_categoriaChanged();
    #endregion
		
		public tb_produto()
		{
			this._categoria = default(EntityRef<categoria>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_produto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_produto
		{
			get
			{
				return this._id_produto;
			}
			set
			{
				if ((this._id_produto != value))
				{
					this.Onid_produtoChanging(value);
					this.SendPropertyChanging();
					this._id_produto = value;
					this.SendPropertyChanged("id_produto");
					this.Onid_produtoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_nome", DbType="NVarChar(50)")]
		public string pro_nome
		{
			get
			{
				return this._pro_nome;
			}
			set
			{
				if ((this._pro_nome != value))
				{
					this.Onpro_nomeChanging(value);
					this.SendPropertyChanging();
					this._pro_nome = value;
					this.SendPropertyChanged("pro_nome");
					this.Onpro_nomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_preco", DbType="Float")]
		public System.Nullable<double> pro_preco
		{
			get
			{
				return this._pro_preco;
			}
			set
			{
				if ((this._pro_preco != value))
				{
					this.Onpro_precoChanging(value);
					this.SendPropertyChanging();
					this._pro_preco = value;
					this.SendPropertyChanged("pro_preco");
					this.Onpro_precoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_marca", DbType="NVarChar(50)")]
		public string pro_marca
		{
			get
			{
				return this._pro_marca;
			}
			set
			{
				if ((this._pro_marca != value))
				{
					this.Onpro_marcaChanging(value);
					this.SendPropertyChanging();
					this._pro_marca = value;
					this.SendPropertyChanged("pro_marca");
					this.Onpro_marcaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_categoria", DbType="Int")]
		public System.Nullable<int> id_categoria
		{
			get
			{
				return this._id_categoria;
			}
			set
			{
				if ((this._id_categoria != value))
				{
					if (this._categoria.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_categoriaChanging(value);
					this.SendPropertyChanging();
					this._id_categoria = value;
					this.SendPropertyChanged("id_categoria");
					this.Onid_categoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="categoria_tb_produto", Storage="_categoria", ThisKey="id_categoria", OtherKey="id_categoria", IsForeignKey=true)]
		public categoria categoria
		{
			get
			{
				return this._categoria.Entity;
			}
			set
			{
				categoria previousValue = this._categoria.Entity;
				if (((previousValue != value) 
							|| (this._categoria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._categoria.Entity = null;
						previousValue.tb_produto.Remove(this);
					}
					this._categoria.Entity = value;
					if ((value != null))
					{
						value.tb_produto.Add(this);
						this._id_categoria = value.id_categoria;
					}
					else
					{
						this._id_categoria = default(Nullable<int>);
					}
					this.SendPropertyChanged("categoria");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
